version: "3"

############################################################
# Docker-Compose for Nginx-Certbot
############################################################

services:

  nginx:
    image: kungalex/nginx-certbot

    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - cert-data:/etc/letsencrypt:rw
      - ./mysite.template:/etc/nginx/sites/mysite.template

    env_file: nginx.env

    ports:
     - "80:80"
     - "443:443"

  # Your app stuff here
  # note see mysite.template for nginx upstream server and port config
  app:
    image: k8s.gcr.io/echoserver:1.4


volumes:
  cert-data:
