version: "2"

############################################################
# Docker-Compose for Nginx-Certbot
############################################################

services:

  nginx:
    build: .
    image: kungalex/nginx-certbot:dev-1.0

    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - cert-data:/etc/letsencrypt:rw

    env_file: nginx.env

    ports:
     - "80:80"
     - "443:443"

   # command: sleep infinity

volumes:
  cert-data:
