version: "2"

############################################################
# Docker-Compose for Nginx-Certbot
############################################################

services:

  nginx:
    build: .
    image: kungalex/nginx-certbot

    volumes:
      - ./sites:/etc/nginx/sites:rw
      - ./snippets:/etc/nginx/snippets/:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./scripts:/etc/nginx/scripts:rw


    env_file: nginx.env

    ports:
     - "80:80"
     - "443:443"

    command: ./scripts/startscript.sh
